<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../ValvePak/ValvePak.snk</AssemblyOriginatorKeyFile>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Files\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.65.51" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValvePak\ValvePak.csproj" />
  </ItemGroup>

</Project>
